# Generated by Django 3.2.9 on 2021-11-04 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_api', '0002_auto_20211105_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='Images/None/No-img.jpg', upload_to='images/'),
        ),
    ]
